#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zks_console
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hrms-eu")]
	public partial class dalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblDeviceLog(tblDeviceLog instance);
    partial void UpdatetblDeviceLog(tblDeviceLog instance);
    partial void DeletetblDeviceLog(tblDeviceLog instance);
    partial void InserttblEmployee_TimeLog(tblEmployee_TimeLog instance);
    partial void UpdatetblEmployee_TimeLog(tblEmployee_TimeLog instance);
    partial void DeletetblEmployee_TimeLog(tblEmployee_TimeLog instance);
    #endregion
		
		public dalDataContext() : 
				base(global::zks_console.Properties.Settings.Default.hrms_euConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblDeviceLog> tblDeviceLogs
		{
			get
			{
				return this.GetTable<tblDeviceLog>();
			}
		}
		
		public System.Data.Linq.Table<tblEmployee_TimeLog> tblEmployee_TimeLogs
		{
			get
			{
				return this.GetTable<tblEmployee_TimeLog>();
			}
		}
		
		public System.Data.Linq.Table<vwDeviceLog> vwDeviceLogs
		{
			get
			{
				return this.GetTable<vwDeviceLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="db_owner.tblDeviceLogs")]
	public partial class tblDeviceLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _DeviceId;
		
		private int _IdNo;
		
		private System.DateTime _LogDate;
		
		private int _Mode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDeviceIdChanging(int value);
    partial void OnDeviceIdChanged();
    partial void OnIdNoChanging(int value);
    partial void OnIdNoChanged();
    partial void OnLogDateChanging(System.DateTime value);
    partial void OnLogDateChanged();
    partial void OnModeChanging(int value);
    partial void OnModeChanged();
    #endregion
		
		public tblDeviceLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Int NOT NULL")]
		public int DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNo", DbType="Int NOT NULL")]
		public int IdNo
		{
			get
			{
				return this._IdNo;
			}
			set
			{
				if ((this._IdNo != value))
				{
					this.OnIdNoChanging(value);
					this.SendPropertyChanging();
					this._IdNo = value;
					this.SendPropertyChanged("IdNo");
					this.OnIdNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate", DbType="DateTime NOT NULL")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this.OnLogDateChanging(value);
					this.SendPropertyChanging();
					this._LogDate = value;
					this.SendPropertyChanged("LogDate");
					this.OnLogDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="Int NOT NULL")]
		public int Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this.OnModeChanging(value);
					this.SendPropertyChanging();
					this._Mode = value;
					this.SendPropertyChanged("Mode");
					this.OnModeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee_TimeLog")]
	public partial class tblEmployee_TimeLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogId;
		
		private int _EmployeeId;
		
		private System.DateTime _TimeLog;
		
		private int _EntryType;
		
		private System.Nullable<int> _DeviceLogId;
		
		private int _Mode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogIdChanging(int value);
    partial void OnLogIdChanged();
    partial void OnEmployeeIdChanging(int value);
    partial void OnEmployeeIdChanged();
    partial void OnTimeLogChanging(System.DateTime value);
    partial void OnTimeLogChanged();
    partial void OnEntryTypeChanging(int value);
    partial void OnEntryTypeChanged();
    partial void OnDeviceLogIdChanging(System.Nullable<int> value);
    partial void OnDeviceLogIdChanged();
    partial void OnModeChanging(int value);
    partial void OnModeChanged();
    #endregion
		
		public tblEmployee_TimeLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogId
		{
			get
			{
				return this._LogId;
			}
			set
			{
				if ((this._LogId != value))
				{
					this.OnLogIdChanging(value);
					this.SendPropertyChanging();
					this._LogId = value;
					this.SendPropertyChanged("LogId");
					this.OnLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this.OnEmployeeIdChanging(value);
					this.SendPropertyChanging();
					this._EmployeeId = value;
					this.SendPropertyChanged("EmployeeId");
					this.OnEmployeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeLog", DbType="DateTime NOT NULL")]
		public System.DateTime TimeLog
		{
			get
			{
				return this._TimeLog;
			}
			set
			{
				if ((this._TimeLog != value))
				{
					this.OnTimeLogChanging(value);
					this.SendPropertyChanging();
					this._TimeLog = value;
					this.SendPropertyChanged("TimeLog");
					this.OnTimeLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryType", DbType="Int NOT NULL")]
		public int EntryType
		{
			get
			{
				return this._EntryType;
			}
			set
			{
				if ((this._EntryType != value))
				{
					this.OnEntryTypeChanging(value);
					this.SendPropertyChanging();
					this._EntryType = value;
					this.SendPropertyChanged("EntryType");
					this.OnEntryTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceLogId", DbType="Int")]
		public System.Nullable<int> DeviceLogId
		{
			get
			{
				return this._DeviceLogId;
			}
			set
			{
				if ((this._DeviceLogId != value))
				{
					this.OnDeviceLogIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceLogId = value;
					this.SendPropertyChanged("DeviceLogId");
					this.OnDeviceLogIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="Int NOT NULL")]
		public int Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this.OnModeChanging(value);
					this.SendPropertyChanging();
					this._Mode = value;
					this.SendPropertyChanged("Mode");
					this.OnModeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="db_owner.vwDeviceLogs")]
	public partial class vwDeviceLog
	{
		
		private int _Id;
		
		private int _DeviceId;
		
		private int _IdNo;
		
		private System.DateTime _LogDate;
		
		private int _Mode;
		
		private int _EmployeeId;
		
		public vwDeviceLog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceId", DbType="Int NOT NULL")]
		public int DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this._DeviceId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNo", DbType="Int NOT NULL")]
		public int IdNo
		{
			get
			{
				return this._IdNo;
			}
			set
			{
				if ((this._IdNo != value))
				{
					this._IdNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate", DbType="DateTime NOT NULL")]
		public System.DateTime LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this._LogDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mode", DbType="Int NOT NULL")]
		public int Mode
		{
			get
			{
				return this._Mode;
			}
			set
			{
				if ((this._Mode != value))
				{
					this._Mode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeId", DbType="Int NOT NULL")]
		public int EmployeeId
		{
			get
			{
				return this._EmployeeId;
			}
			set
			{
				if ((this._EmployeeId != value))
				{
					this._EmployeeId = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
