//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UareU.Kiosk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ServerTimeQueryInterval {
            get {
                return ((int)(this["ServerTimeQueryInterval"]));
            }
            set {
                this["ServerTimeQueryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LongTimeFormat {
            get {
                return ((bool)(this["LongTimeFormat"]));
            }
            set {
                this["LongTimeFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("...")]
        public string OfflineMessage {
            get {
                return ((string)(this["OfflineMessage"]));
            }
            set {
                this["OfflineMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TerminalId {
            get {
                return ((int)(this["TerminalId"]));
            }
            set {
                this["TerminalId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DataDownloadInterval {
            get {
                return ((int)(this["DataDownloadInterval"]));
            }
            set {
                this["DataDownloadInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PostOfflineLogsInterval {
            get {
                return ((int)(this["PostOfflineLogsInterval"]));
            }
            set {
                this["PostOfflineLogsInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Fullview {
            get {
                return ((bool)(this["Fullview"]));
            }
            set {
                this["Fullview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseServerTime {
            get {
                return ((bool)(this["UseServerTime"]));
            }
            set {
                this["UseServerTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int MaxLogDispayTime {
            get {
                return ((int)(this["MaxLogDispayTime"]));
            }
            set {
                this["MaxLogDispayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int DeviceReconnectInterval {
            get {
                return ((int)(this["DeviceReconnectInterval"]));
            }
            set {
                this["DeviceReconnectInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DataDownloadEnabled {
            get {
                return ((bool)(this["DataDownloadEnabled"]));
            }
            set {
                this["DataDownloadEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableUSBDevice {
            get {
                return ((bool)(this["EnableUSBDevice"]));
            }
            set {
                this["EnableUSBDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableLANDevice {
            get {
                return ((bool)(this["EnableLANDevice"]));
            }
            set {
                this["EnableLANDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("securedmanpower.com")]
        public string AppUrl {
            get {
                return ((string)(this["AppUrl"]));
            }
            set {
                this["AppUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\KIOSK FILES\\TimeLogs")]
        public string TimeLogsPath {
            get {
                return ((string)(this["TimeLogsPath"]));
            }
            set {
                this["TimeLogsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\KIOSK FILES\\Datasource")]
        public string OfflineDataPath {
            get {
                return ((string)(this["OfflineDataPath"]));
            }
            set {
                this["OfflineDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PhotosVersion {
            get {
                return ((string)(this["PhotosVersion"]));
            }
            set {
                this["PhotosVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\KIOSK FILES\\Photos")]
        public string PhotosPath {
            get {
                return ((string)(this["PhotosPath"]));
            }
            set {
                this["PhotosPath"] = value;
            }
        }
    }
}
